apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e7mup8myv-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-9d19d69214.uwxi.p3.openshiftapps.com/rhtap/rhtap-qe:250e7b6a765671378b462a531b76394169c0d535@sha256:673639ee54347aaaa27bad8703948bfb8a5b7ed557279cd0c74613283ec691bf
          name: container-image
